global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Fresh Market API
  - job_name: 'fresh-market-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fresh-market-api:8080']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MySQL Exporter (optional, can be added later)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']

  # Redis Exporter (optional, can be added later)  
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093