# 生产环境配置
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fresh_market_prod?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8}
    username: ${DB_USERNAME:freshmarket}
    password: ${DB_PASSWORD:freshmarket123}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis123}
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5

# JWT配置
jwt:
  secret: ${JWT_SECRET:fresh-market-production-secret-key-2024-very-long-and-secure-please-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000}  # 24小时

# 日志配置
logging:
  level:
    root: WARN
    com.freshmarket: INFO
    org.springframework.security: WARN
  file:
    name: ${LOG_FILE:/var/log/fresh-market.log}
    max-size: 100MB
    max-history: 30

# Actuator配置 (生产环境限制暴露的端点)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

# 任务队列配置  
task:
  queue:
    polling-interval: ${TASK_POLLING_INTERVAL:5000}
    batch-size: ${TASK_BATCH_SIZE:20}
    max-retry: ${TASK_MAX_RETRY:3}

# 服务器配置
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  tomcat:
    max-threads: 200
    min-spare-threads: 10