# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh_market_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: freshmarket
    password: freshmarket123
    
  jpa:
    hibernate:
      ddl-auto: create-drop  # 测试时自动创建和删除表
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
  flyway:
    enabled: false  # 测试时禁用，使用Hibernate DDL
      
  redis:
    # 测试环境使用嵌入式Redis
    port: 0
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

# JWT配置 (测试环境)
jwt:
  secret: ${JWT_SECRET_TEST:test-secret-key-for-unit-testing-must-be-long-enough-for-hmac-sha256-algorithm}
  expiration: 60000  # 1分钟，便于测试过期场景

# 日志配置
logging:
  level:
    root: WARN
    com.freshmarket: INFO
    org.hibernate: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 任务队列配置  
task:
  queue:
    polling-interval: 1000  # 测试环境快速轮询
    batch-size: 2
    max-retry: 1